document.getElementById("container").style.backgroundColor="#12406A"
document.querySelectorAll(".div")[0].style.backgroundColor="#EB8F90"
document.querySelectorAll(".div")[1].style.backgroundColor="#FFB471"
document.querySelectorAll(".div")[2].style.backgroundColor="#ADBED2"
document.body.style.backgroundColor="#CCFFFF"